version: '3.7'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - vayer-electric-network

  frontend:
    image: vayer/vayer-electric-frontend:a1da7b9
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - vayer-electric-backend
    networks:
      - vayer-electric-network

  vayer-electric-backend:
    image: vayer/vayer-electric-backend:9e733d6
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db
    ports:
      - 8080:8080
    networks:
      - vayer-electric-network
    depends_on:
      - db

  # TODO - use images from docker hub
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    networks:
      - vayer-electric-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  vayer-electric-network:
    driver: bridge
